services:
  api:
    build: .
    container_name: finbuddy-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: finbuddy_user
      DB_PASSWORD: finbuddy_pass
      DB_NAME: finbuddy_db
      APP_ENV: development
    depends_on:
      - db
    networks:
      - finbuddy-net
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: finbuddy-db
    environment:
      POSTGRES_USER: finbuddy_user
      POSTGRES_PASSWORD: finbuddy_pass
      POSTGRES_DB: finbuddy_db
    ports:
      - "5432:5432"
    volumes:
      - finbuddy-data:/var/lib/postgresql/data
    networks:
      - finbuddy-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finbuddy_user -d finbuddy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  finbuddy-net:

volumes:
  finbuddy-data:
